FROM python:3.8-slim-buster

COPY . /app
COPY ./environment .


RUN pip install -r pip_env.txt

WORKDIR /app

EXPOSE 80


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--use-colors", "--factory"]
